/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop.orb;
import java.sql.Connection;
import java.util.Vector;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.Desktop;
import java.io.File;
import java.sql.*;
import java.util.List;
import java.util.Arrays;
import java.util.ArrayList;
import java.io.*;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.Timer; // For the Timer class
import java.awt.event.ActionEvent; // For the ActionEvent class
import java.text.SimpleDateFormat; // For formatting the time
import java.util.Date; // For getting the current date and time

/**
 *
 * @author Charles Montero
 */
public class AdminManagement extends javax.swing.JFrame {
    private Connection conn;
    private String fullName;
    private String email;
    private Timer timer;
    private File currentDirectory;
    private File parentDirectory;
    /**
     * Creates new form AdminManagement
     */
    public AdminManagement(String email, String fullName) {
        this.fullName = fullName;  
        this.email = email;
        initComponents();
        currentDirectory = new File("C:/Notes");
        if (!currentDirectory.exists()) {
            JOptionPane.showMessageDialog(this, "Root directory E:/Notes does not exist.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit the constructor if the directory doesn't exist
        }
        connectToDatabase();
        setLocationRelativeTo(null);
        startClock();
        loadUserFolders(); 
    }
    
    private void startClock() {
        timer = new Timer(1000, (ActionEvent e) -> {
            String currentTime = getCurrentTime();
            jLabel2.setText(currentTime); // Update jLabel2 with the current time
        });
        timer.start(); // Start the timer
    }

    private String getCurrentTime() {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        return sdf.format(new Date());
    }

    private void loadUserFolders() {
        if (currentDirectory != null && currentDirectory.exists()) {
            // Get all the subdirectories (user folders) and PDF files inside the current directory
            File[] files = currentDirectory.listFiles(file -> file.isDirectory() || file.getName().endsWith(".pdf"));

            // Update JTable to display folder names and PDFs
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Clear existing rows

            // If we're inside a user folder, allow going back to the parent folder
            if (parentDirectory != null) {
                model.addRow(new Object[] { ".." }); // Add ".." to go back to the parent folder
            }

            // Add user folders and PDFs to the table
            for (File file : files) {
                model.addRow(new Object[] { file.getName() });
            }
        } else {
            JOptionPane.showMessageDialog(this, "Current directory is invalid or does not exist.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    private void connectToDatabase() {
        try {
            String dbUrl = "jdbc:mysql://localhost:3306/OrbRegisters?allowPublicKeyRetrieval=true&useSSL=false";
            String dbUser = "root"; // Your database username
            String dbPassword = "yourpassword"; // Your database password
            conn = DriverManager.getConnection(dbUrl, dbUser, dbPassword);  // Establish connection
            System.out.println("Database connected successfully.");
        } catch (SQLException e) {
            e.printStackTrace(System.out);
            JOptionPane.showMessageDialog(this, "Failed to connect to the database.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("00:00:00");
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // Set font size
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); // Center-align text
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 20, 200, 30); // Set position and size (example)

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Time");

        jButton3.setText("LOG OUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/orb/3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(58, 58, 58)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMIN");

        jButton1.setText("ADD");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OPEN");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PDF MASTERLIST"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton4.setText("UPDATE");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("DELETE");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        LoginMenu loginMenu = new LoginMenu(); // Create a new instance of LoginMenu
        loginMenu.setVisible(true); // Show the login menu
        this.dispose(); // Close the current window (PDFManagement)
    }//GEN-LAST:event_jButton3ActionPerformed

        private String[] getUserNames() {
        List<String> userNamesList = new ArrayList<>();
        String dbUrl = "jdbc:mysql://localhost:3306/OrbRegisters?useSSL=false";
        String dbUser = "root";
        String dbPassword = "yourpassword";
        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            conn = DriverManager.getConnection(dbUrl, dbUser, dbPassword);
            String query = "SELECT DISTINCT user_name FROM pdfs"; // Modify if you have a separate users table
            stmt = conn.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                userNamesList.add(rs.getString("user_name"));
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (stmt != null) stmt.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }

        return userNamesList.toArray(new String[0]);
    }
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // File Chooser to select PDF file
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("PDF Files", "pdf"));

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            if (!selectedFile.getName().endsWith(".pdf")) {
                JOptionPane.showMessageDialog(this, "Please select a valid PDF file.", "Invalid File", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Prompt the admin to choose the target user's folder
            String[] userNames = getUserNames(); // This method should return an array of user names (from the database or list of users)

            // Add the admin to the user list if not already present
            List<String> userList = new ArrayList<>(Arrays.asList(userNames));
            String adminUser = "Christian Maderazo"; // This is the admin username, modify it to match your actual admin username
            if (!userList.contains(adminUser)) {
                userList.add(0, adminUser); // Add the admin user at the top of the list
            }

            String[] updatedUserNames = userList.toArray(new String[0]);

            String selectedUser = (String) JOptionPane.showInputDialog(
                this, 
                "Select a user to add the PDF to:", 
                "Select User", 
                JOptionPane.QUESTION_MESSAGE, 
                null, 
                updatedUserNames, 
                updatedUserNames[0] // Default selected user
            );

            if (selectedUser == null || selectedUser.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select a user.", "User Selection Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Proceed with adding the PDF to the selected user's folder
            String targetDirectory = "C:\\Notes\\" + selectedUser + "\\"; // Use the selected user's folder
            File targetFolder = new File(targetDirectory);

            // Create the folder if it doesn't exist
            if (!targetFolder.exists()) {
                if (!targetFolder.mkdirs()) {
                    JOptionPane.showMessageDialog(this, "Error creating the target folder.", "Folder Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // Define the destination file path
            File destinationFile = new File(targetFolder, selectedFile.getName());

            // Copy the selected file to the target folder
            try {
                Files.copy(selectedFile.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);

                // Insert the selected PDF into the database (storing the filename and the user it belongs to)
                String dbUrl = "jdbc:mysql://localhost:3306/OrbRegisters?useSSL=false";
                String dbUser = "root";
                String dbPassword = "yourpassword";
                Connection conn = DriverManager.getConnection(dbUrl, dbUser, dbPassword);
                PreparedStatement stmt = null;

                // Insert the PDF into the database with the selected user's name
                String insertSql = "INSERT INTO pdfs (filename, user_name) VALUES (?, ?)";
                stmt = conn.prepareStatement(insertSql);
                stmt.setString(1, selectedFile.getName()); // PDF name
                stmt.setString(2, selectedUser); // Selected user's name

                int rowsInserted = stmt.executeUpdate();
                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(this, "PDF added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    loadUserFolders();
                    //updatePDFList(); // Define this method to refresh the displayed PDF list
                }

                stmt.close();
                conn.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error copying the file: " + e.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error inserting into database: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Get the selected row index
        int selectedRow = jTable1.getSelectedRow();

        // Check if a row is selected
        if (selectedRow != -1) {
            // Get the item name from the first column
            String selectedItem = (String) jTable1.getValueAt(selectedRow, 0);

            // Construct the file path using the selected item and the current directory
            String filePath = currentDirectory.getPath() + "/" + selectedItem;

            File file = new File(filePath);

            // Check if the selected item is a directory
            if (file.isDirectory()) {
                // If it's a folder, navigate into it and reload the table
                parentDirectory = currentDirectory;  // Store the current directory as the parent
                currentDirectory = file;  // Update the current directory to the selected folder
                loadUserFolders();  // Reload the table to show the contents of the folder
            } else if (file.exists()) {
                // If it's a PDF file, open it
                try {
                    Desktop.getDesktop().open(file);  // Open the PDF file if it exists
                } catch (IOException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Error opening PDF.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // If neither a file nor folder, show an error
                JOptionPane.showMessageDialog(this, "The selected item does not exist.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // If no item is selected, show an error
            JOptionPane.showMessageDialog(this, "No item selected.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

         int selectedRow = jTable1.getSelectedRow();
         if (selectedRow == -1) {
             JOptionPane.showMessageDialog(this, "Please select a user to update.", "Error", JOptionPane.ERROR_MESSAGE);
             return;
         }

         // Get the current username from the selected row (assuming username is in the first column)
         String currentUserName = (String) jTable1.getValueAt(selectedRow, 0); 

         // Prompt the user to choose a new role
         String[] roles = {"user", "VIP"};
         String newRole = (String) JOptionPane.showInputDialog(
             this,
             "Select the new role for " + currentUserName + ":",
             "Change Role",
             JOptionPane.QUESTION_MESSAGE,
             null,
             roles,
             "user" // Default role
         );

         if (newRole == null) {
             return; // No role selected, exit
         }

         // Confirm the role change
         int confirmation = JOptionPane.showConfirmDialog(
             this,
             "Are you sure you want to change the role of \"" + currentUserName + "\" to \"" + newRole + "\"?",
             "Confirm Role Change",
             JOptionPane.YES_NO_OPTION
         );

         if (confirmation == JOptionPane.YES_OPTION) {
             // Update the role in the database
             try (Connection conn = DBConnect.getConnection();
                  PreparedStatement stmt = conn.prepareStatement(
                      "UPDATE users SET role = ? WHERE fullname = ?")) {

                 stmt.setString(1, newRole); // Set new role
                 stmt.setString(2, currentUserName); // Set current username
                 int rowsAffected = stmt.executeUpdate();

                 if (rowsAffected > 0) {
                     // If role update is successful, update the JTable
                     jTable1.setValueAt(newRole, selectedRow, 1); // Update the role in the second column of the table
                     JOptionPane.showMessageDialog(this, "User role updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                 } else {
                     JOptionPane.showMessageDialog(this, "Error updating the user role in the database.", "Error", JOptionPane.ERROR_MESSAGE);
                 }
             } catch (SQLException e) {
                 e.printStackTrace();
                 JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
             }
         }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow != -1) {  // Check if a row (file) is selected
            // Get the file name from the selected row (assuming "File Name" is the first column)
            String fileName = jTable1.getValueAt(selectedRow, 0).toString();

            // Get the current path of the directory (this should be the folder you are in)
            String folderPath = currentDirectory.getPath();  // Current folder (e.g., Charles Montero)

            // Database connection
            Connection conn = null;
            PreparedStatement stmt = null;

            try {
                // Database URL and credentials
                String dbUrl = "jdbc:mysql://localhost:3306/OrbRegisters?allowPublicKeyRetrieval=true&useSSL=false";
                String dbUser = "root";
                String dbPassword = "yourpassword";

                // Establish connection
                conn = DriverManager.getConnection(dbUrl, dbUser, dbPassword);

                // Query to delete the entry from the database
                String deleteSQL = "DELETE FROM pdfs WHERE filename = ?";
                stmt = conn.prepareStatement(deleteSQL);
                stmt.setString(1, fileName);
                stmt.executeUpdate(); // Execute the delete query

                // File path where the PDF is stored, based on the current directory
                String filePath = folderPath + "/" + fileName;  // Construct the file path from the current folder
                File file = new File(filePath);

                // Delete the file from the folder
                if (file.exists()) {
                    boolean deleted = file.delete();
                    if (deleted) {
                        JOptionPane.showMessageDialog(this, "Note deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Error deleting the file from the folder.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "File not found in the folder.", "Error", JOptionPane.ERROR_MESSAGE);
                }

                // Remove the row from the table
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.removeRow(selectedRow);

            } catch (SQLException e) {
                // Handle SQL exceptions
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            } finally {
                // Close database resources
                try {
                    if (stmt != null) stmt.close();
                    if (conn != null) conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error closing resources: " + ex.getMessage(), "Resource Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            // If no file is selected, ask if the admin wants to delete a user
            int confirmDeleteUser = JOptionPane.showConfirmDialog(this, "No file selected. Do you want to delete a user?", "Delete User", JOptionPane.YES_NO_OPTION);

            if (confirmDeleteUser == JOptionPane.YES_OPTION) {
                // Retrieve the list of users excluding admin from the database
                Connection conn = null;
                Statement stmt = null;
                ResultSet rs = null;
                try {
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/OrbRegisters?allowPublicKeyRetrieval=true&useSSL=false", "root", "yourpassword");
                    stmt = conn.createStatement();

                    // Query to get all users excluding admin
                    String query = "SELECT fullname FROM users WHERE fullname != 'admin'"; // Exclude admin
                    rs = stmt.executeQuery(query);

                    // Collect the list of user names
                    Vector<String> userList = new Vector<>();
                    while (rs.next()) {
                        userList.add(rs.getString("fullname"));
                    }

                    // If there are no users to delete, show a message and return
                    if (userList.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "No users available for deletion.", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    // Show a dialog to select a user
                    String selectedUser = (String) JOptionPane.showInputDialog(this, "Select a user to delete:", "Delete User", JOptionPane.PLAIN_MESSAGE, null, userList.toArray(), userList.get(0));

                    if (selectedUser != null) {
                        // Delete the user folder and database entry
                        File userFolder = new File("C:\\Notes\\" + selectedUser); // Adjust path as needed
                        if (userFolder.exists()) {
                            boolean folderDeleted = deleteDirectory(userFolder);
                            if (folderDeleted) {
                                JOptionPane.showMessageDialog(this, "User folder deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                            } else {
                                JOptionPane.showMessageDialog(this, "Error deleting user folder.", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        }

                        // Delete user from database
                        PreparedStatement deleteUserStmt = conn.prepareStatement("DELETE FROM users WHERE fullname = ?");
                        deleteUserStmt.setString(1, selectedUser);
                        deleteUserStmt.executeUpdate();

                        // Show success message
                        JOptionPane.showMessageDialog(this, "User deleted successfully from database.", "Success", JOptionPane.INFORMATION_MESSAGE);

                    }

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                } finally {
                    try {
                        if (rs != null) rs.close();
                        if (stmt != null) stmt.close();
                        if (conn != null) conn.close();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, "Error closing resources: " + ex.getMessage(), "Resource Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton5MouseClicked

        // Method to delete a directory and its contents
    private boolean deleteDirectory(File directory) {
        if (directory.isDirectory()) {
            String[] files = directory.list();
            if (files != null) {
                for (String file : files) {
                    File childFile = new File(directory, file);
                    if (!deleteDirectory(childFile)) {
                        return false;
                    }
                }
            }
        }
        return directory.delete();
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void updatePDFList() {
        // Path to the folder
        String folderPath = "C:/Notes/" + this.fullName + "/";

        // Create a new DefaultTableModel with a column for filenames
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("File Name");  // Adding a column for file names

        try (Statement stmt = conn.createStatement()) {
            // Query the database to get the list of PDFs
            ResultSet rs = stmt.executeQuery("SELECT filename FROM pdfs");

            // Loop through the result set and add each filename as a new row in the table
            while (rs.next()) {
                String fileName = rs.getString("filename");
                File file = new File(folderPath + fileName); // Construct the full path to the PDF

                // Check if the file exists in the specified folder
                if (file.exists() && file.isFile() && file.getName().endsWith(".pdf")) {
                    tableModel.addRow(new Object[] { fileName });  // Add a new row with the file name
                }
            }

            // Set the table model to the JTable
            jTable1.setModel(tableModel);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error occurred while retrieving PDFs.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
